spring.application.name=lostandfound
spring.datasource.url=jdbc:mysql://switchback.proxy.rlwy.net:47449/railway
spring.datasource.username=root
spring.datasource.password=NUgiOyfWLgJUGXwnPQWzPOJkDXcdmlpf
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# Email settings for Findify notifications
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreply.findify@gmail.com
spring.mail.password=dwsrvjzvlhjhrplj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
